model_path: "./data/models/best.pt"
classes:
  - helmet
  - no_helmet
  - pedestrian
  - motorcyclist
  - stopline
  - green
  - yellow
  - red
  - bus
  - truck
confidence_threshold: 0.25
nms_threshold: 0.4
input_size: [640, 640]